spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cursed_ps"
    username: Valentin
    password: 12pflhfk
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: validation
server:
  port: 80